### ISSUE TITLE
D3 wording

### ISSUE THREAD

**Issue by stm107** [laboon/CS1632_Spring2019#32] opened 2019-04-01 13:33 UTC

**Comment by stm107** [comment] 2019-04-02 02:23
Reopening. Typo in deliverable 3, requirement 6. "include three additional columns" should say "include 4 additional columns."

**Comment by laboon** [comment] 2019-04-02 11:31
The defect appears to be fixed from my end.  You can re-close this unless you still see the defect appearing.  You can still get credit even if the issue is closed.

**Closed as completed** 2019-04-02 12:50 UTC
